### PR TITLE
updating for Uint8List

### PR DESCRIPTION
**Pull request by jodinathan**

### CODE REVIEW

**Comment by isoos** [comment]
Does this trigger an SDK dependency change?

**Comment by jodinathan** [comment]
I guess not but I really don't know.
I have upgraded my mac to Catalina and I had to upgrade dart because of that.

**Comment by isoos** [comment]
> I guess not but I really don't know.

Okay, a follow-up question: why do this change? Did you get an error somewhere?

**Comment by jodinathan** [comment]
```
Unhandled exception:
type '_StreamHandlerTransformer<List<int>, Frame>' is not a subtype of type 'StreamTransformer<Uint8List, Frame>' of 'streamTransformer'
#0      Stream.transform (dart:async/stream.dart)
#1      _FrameStreamTransformer.parseFrames (package:cassandart/src/frames.dart:82:18)
```

**Comment by isoos** [comment]
Okay, thanks! Do you want me to release this as a new version or do you have other changes in mind?

**Comment by jodinathan** [comment]
Nope, just to be able to use dart 2.5.
I should push an app to production in a day or two, if anything comes I will create another PR.

**Comment by isoos** [comment]
published 0.1.2

**Pull request merged**
